---
# tasks file for roles/windows-services

- name: Installer les fonctionnalités Active Directory et DNS
  ansible.windows.win_feature:
    name:
      - AD-Domain-Services
      - DNS
    include_management_tools: yes
    state: present
  register: feature_install
  when: server_role == 'domain_controller'

- name: Redémarrer le serveur si nécessaire après l'installation des fonctionnalités
  ansible.windows.win_reboot:
  when: feature_install.reboot_required

- name: Promouvoir le serveur en Contrôleur de Domaine
  ansible.windows.win_domain_controller:
    dns_domain_name: "{{ ad_domain_name }}"
    domain_admin_user: "{{ ansible_user }}"
    domain_admin_password: "{{ ansible_password }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
    state: domain_controller
  register: dc_promo
  when: server_role == 'domain_controller'

- name: Redémarrer le serveur après la promotion en DC
  ansible.windows.win_reboot:
  when: dc_promo.reboot_required

- name: Installer les logiciels demandés via Chocolatey
  community.windows.win_chocolatey:
    name: "{{ item }}"
    state: present
  loop: "{{ software_to_install | default([]) }}"
  when: software_to_install is defined